name: Terraform CI

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch of the upstream repository

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.7  # Specify your Terraform version here

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      # Add any other necessary steps here
